name: CI

on: [pull_request]

jobs:
  build:

    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode 15 beta
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    - name: Run tests
      run: swift test
