name: CI

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode 11 beta
      run: xcode-select -s /Applications/Xcode_11.app
    - name: Run tests
      run: swift test
